### ISSUE TITLE
Pip install on Ubuntu 16.04.6 LTS fails

### ISSUE THREAD

**Issue by zivshapiraintel** [mutpy/astmonkey#21]
Error in pip install (also pip3)

pip3 install astmonkey
Collecting astmonkey
  Downloading astmonkey-0.3.6.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-91zgj0g2/astmonkey/setup.py'"'"'; __file__='"'"'/tmp/pip-install-91zgj0g2/astmonkey/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-91zgj0g2/astmonkey/pip-egg-info
         cwd: /tmp/pip-install-91zgj0g2/astmonkey/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-91zgj0g2/astmonkey/setup.py", line 7, in <module>
        long_description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 3079: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

More details

+ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename: xenial

python3 --version
Python 3.6.10

python --version
Python 3.6.10

**Comment by Farek** [comment]
Hi,
Problem seems to be in `README.md` file that has some bad characters.
I was able to install it with little workaround without looking for bad character. Download latest package from: https://pypi.org/project/astmonkey/#files. 
Untar package with:
`tar -zxvf astmonkey-0.3.6.tar.gz`
Modify setup.py with these two steps:
1. Remove these lines:
`with open('README.rst') as f:
    long_description = f.read()`
2. Modify this line:
`    long_description="Here should be description",`

Now remove old .tar.gz and create new one with modified file:
`tar cvfz astmonkey-0.3.6.tar.gz astmonkey-0.3.6/`
Install new package with pip:
`pip install astmonkey-0.3.6.tar.gz`

And thats it :)
