### ISSUE TITLE
Broken under Python 3.4

### ISSUE THREAD

**Issue by AnnanFay** [mutpy/astmonkey#3]
I'm leaving this note here for anyone trying to get this working and so the errors are searchable from Google.

The code is broken under Python 3.4 and gives some opaque error messages (listed below). The code still works under 3.3 so downgrading works.

```

.............FF.....................E..............s..ss...............
======================================================================
ERROR: test_function_def (astmonkey.tests.test_visitors.SourceGeneratorNodeVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/........../astmonkey/tests/test_visitors.py", line 86, in test_function_def
    self.assert_code_equal('def foo(x, y=1, *args, **kwargs):\n\tpass')
  File "/home/........../astmonkey/tests/test_visitors.py", line 58, in assert_code_equal
    generated = visitors.to_source(node, indent_with='\t')
  File "/home/........../astmonkey/visitors.py", line 123, in to_source
    generator.visit(node)
  File "/home/........../.pyenv/versions/3.4.3/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/home/........../.pyenv/versions/3.4.3/lib/python3.4/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/home/........../.pyenv/versions/3.4.3/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/home/........../astmonkey/visitors.py", line 245, in visit_FunctionDef
    self.signature(node.args)
  File "/home/........../astmonkey/visitors.py", line 193, in signature
    self.write('*' + node.vararg)
TypeError: Can't convert 'arg' object to str implicitly

======================================================================
FAIL: test_assert_with_message (astmonkey.tests.test_visitors.SourceGeneratorNodeVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/........../astmonkey/tests/test_visitors.py", line 245, in test_assert_with_message
    self.assert_code_equal("assert True, 'message'")
  File "/home/........../astmonkey/tests/test_visitors.py", line 59, in assert_code_equal
    self.assertEqual(code, generated)
AssertionError: "assert True, 'message'" != "assert , 'message'"
- assert True, 'message'
?        ----
+ assert , 'message'


======================================================================
FAIL: test_assert_without_message (astmonkey.tests.test_visitors.SourceGeneratorNodeVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/........../astmonkey/tests/test_visitors.py", line 248, in test_assert_without_message
    self.assert_code_equal("assert True")
  File "/home/........../astmonkey/tests/test_visitors.py", line 59, in assert_code_equal
    self.assertEqual(code, generated)
AssertionError: 'assert True' != 'assert '
- assert True
?        ----
+ assert 


----------------------------------------------------------------------
Ran 71 tests in 0.012s

FAILED (failures=2, errors=1, skipped=3)
```

**Comment by phihos** [comment]
This should be fixed by PR #4. This repository is now actively maintained again. So if you have any more issues, don't hesitate to tell us :-)
